name: Release
on:
  push:
    branches:
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Decode keystore
        run: |
          echo "${{ secrets.WEATHERAPP_RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg --batch --passphrase "${{ secrets.WEATHERAPP_UPLOAD_KEY_PASSWORD }}" -d -o release.keystore release.keystore.asc
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          WEATHERAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.WEATHERAPP_UPLOAD_KEY_PASSWORD }}
          WEATHERAPP_UPLOAD_KEY_ALIAS: ${{ secrets.WEATHERAPP_UPLOAD_KEY_ALIAS }}
          WEATHERAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.WEATHERAPP_UPLOAD_STORE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
