name: Scheduled Job

on:
  schedule:
    - cron: '15 */2 * * *'
  workflow_dispatch:

jobs:
  scheduled-job:
    name: Interim Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: yarn
      - name: Release Interim build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
